import React, {useEffect, useMemo, useState, useSyncExternalStore} from 'react';
import {createRoot} from 'react-dom/client';
import {createStore, learningDecision, playbackKey} from './state.mjs';
import {scenario} from './scenario.mjs';
import {copy} from './copy.mjs';
import {artifactMarkdown} from './artifact-export.mjs';
import {mountPlugin, openPath} from './plugin-adapter.jsx';
import './vendor/question-card.css';
import './styles.css';
import './screens.css';

const store=createStore(), plugin=mountPlugin(store), OriginalPlugin=plugin.Component;
const act=(type,values={})=>store.dispatch({type,...values});
const currentArtifact=s=>s.artifacts[s.artifactVersion-1]||s.artifacts.at(-1);
function Icon({kind}){return <svg className="ui-icon" viewBox="0 0 24 24" aria-hidden="true"><path d={{settings:'M4 7h16M4 17h16M8 4v6M16 14v6',history:'M4 4v6h6M5 15a8 8 0 1 0 2-8M12 8v5l3 2',file:'M7 3h7l4 4v14H6V3h1M14 3v5h4M9 12h6M9 16h6',plug:'M8 3v5M16 3v5M6 8h12v3a6 6 0 0 1-12 0V8M12 17v4',close:'M6 6l12 12M18 6L6 18'}[kind]}/></svg>}
function Button({children,primary=false,...props}){return <button className={`action ${primary?'primary':''}`} {...props}>{children}</button>}
function Card({title,eyebrow,children,footer,question=false,className=''}){return <section className={`Mbwy4a_card screen-card ${className}`} aria-label={title} {...(question?{'data-question-key':title}:{})}><header className="Mbwy4a_header">{eyebrow&&<div className="Mbwy4a_eyebrow">{eyebrow}</div>}<h2 className="Mbwy4a_title">{title}</h2></header><div className="Mbwy4a_body">{children}</div>{footer&&<footer className="Mbwy4a_footer">{footer}</footer>}</section>}
function Modes({s}){return <div className="hil-segment mode-choices" role="group" aria-label="本次参与模式">{Object.entries(copy.modes).map(([value,[label,hint]])=><button key={value} title={hint} className={`hil-segment-btn ${s.taskProfile.participationGoal===value?'active':''}`} aria-pressed={s.taskProfile.participationGoal===value} onClick={()=>act('UPDATE_TASK_PROFILE',{taskProfile:{participationGoal:value}})}>{label}</button>)}</div>}
function Install({s}){const busy=s.phase==='installing';return <Card className="install-card" title="给你的 Agent，加上 YourTurn。" footer={busy?<Playback s={s}/>:<Button primary onClick={()=>act('INSTALL_PLUGIN')}><Icon kind="plug"/>启用 YourTurn</Button>}><p className="screen-lead">Agent 继续做事，值得你判断时叫你回来。</p><div className="agent-host"><div className="host-heading"><img className="dsh-whale host-whale" src="./deepseek-logo.svg" alt="DeepSeek"/><div><strong>DeepSeek Harness</strong><span>你的 Agent</span></div></div><div className="host-work"><span/><span/><span/></div><div className={`plugin-slot ${busy?'connected':''}`}><img className="yourturn-logo" src="./yourturn-logo.png" alt="YourTurn"/><span>{busy?'正在加入':'参与判断的插件'}</span><b>{busy?'✓':'＋'}</b></div></div><div className="plugin-capabilities"><span>该自动的继续</span><span>该问你的留给你</span></div></Card>}
function Onboarding({s}){return <Card className="intro-card" title="这次，陪 Dawn 备一堂课。" footer={<Button primary onClick={()=>act('START_DEMO')}>开始备课 →</Button>}><div className="intro-person"><img src={copy.portrait} alt="Dawn：戴眼镜、扎发髻、端着杯子的黑色简笔画"/><div><h3>Dawn</h3><p>毕业一年 · 企业培训讲师</p><p>有点内向，却要亲自面对客户。<br/>领导希望她讲得自信，也练出自己的讲课逻辑。</p></div></div><p className="task-brief">给银行客户讲 60 分钟 AI 办公。</p><blockquote className="dawn-request">“讲课逻辑以后都留给我定。准备资料，你来。”</blockquote><Modes s={s}/></Card>}
const questionTitles={main:'这 60 分钟，按什么逻辑讲？',relation:'工具之间的关系，怎么讲更清楚？',interaction:'哪种互动，你在现场说得自然？'};
function Recall({s,onNote}){const kind=s.phase,choice=s[`${kind}Choice`],options=kind==='main'?scenario.mainOptions:kind==='relation'?scenario.relationOptions:scenario.interactionOptions;return <Card question title={questionTitles[kind]} footer={<><Button onClick={onNote}>补充想法</Button><Button primary onClick={()=>act({main:'ANSWER_MAIN',relation:'ANSWER_RELATION',interaction:'ANSWER_INTERACTION'}[kind],{choice,note:s[`${kind}Note`]})}>采用这个判断 →</Button></>}><p className="recall-reason">{kind==='main'?(s.retainedJudgments.main?copy.growth:'讲课逻辑，关系到你能不能把整堂课带好。这次按你的参与设置，把这一判断留给你。'):kind==='interaction'?copy.expression:'你希望多练习判断，这一页的讲法也交给你拿定。'}</p><div className="Mbwy4a_options" role="group" aria-label="可选答案">{options.map(([label,detail],i)=><button key={label} className={`Mbwy4a_option ${choice===i?'Mbwy4a_optionSelected':''}`} aria-pressed={choice===i} onClick={()=>act('ANSWER_DRAFT',{choice:i})}><span className="Mbwy4a_number">{choice===i?'✓':i+1}</span><span className="Mbwy4a_optionCopy"><span className="Mbwy4a_optionLabel">{label}</span>{choice===i&&<span className="Mbwy4a_description">{detail}</span>}</span></button>)}</div>{kind==='main'&&<div className="retained-line"><span>✓</span>{s.retainedJudgments.main?'已记住：这类讲课逻辑，每次都问你。':'本次按参与设置决定是否邀请。'}</div>}</Card>}
function Playback({s}){return <div className="playback-controls"><span className={`playback-dot ${s.playbackPaused?'paused':''}`}/><span>{s.playbackPaused?'已暂停':'Auto · Agent 正在推进'}</span><button onClick={()=>act('TOGGLE_PLAYBACK')}>{s.playbackPaused?'继续':'暂停'}</button></div>}
function locateCase(){openPath();requestAnimationFrame(()=>[...document.querySelectorAll('.hil-node')].find(el=>el.querySelector('.hil-node-title')?.textContent?.startsWith('3. '))?.click());}
function Execution({s}){const candidate=['candidate','assessed','autoRelation'].includes(s.phase),recalled=s.recallDecisions.findLast(d=>d.nodeId==='relation')?.action==='RECALL';const title={path:'Agent 已排好准备工作的顺序',auto:'先把资料核对清楚',autoMain:'Agent 沿用已知偏好安排主线',candidate:'这一步，也要问你吗？',assessed:recalled?'这一步，也留给你试':'判断过了，这次不打扰',autoRelation:'工具关系页已完成',autoInteraction:'沿用你的习惯，准备低压力的开场',clientChange:'不用从头来，只改受影响的部分。',rerunning:`正在更新：${s.nodes[s.rerunIndex]?.title}`}[s.phase];return <Card title={title} footer={s.phase==='clientChange'?<Button primary onClick={locateCase}>找到「课堂用什么例子」 →</Button>:<Playback s={s}/>}>
{s.phase==='path'&&<><p className="screen-lead">准备工作交给 Agent。讲课逻辑和现场表达，在该问的时候留给你。</p><div className="path-preview">{s.nodes.map(n=><span key={n.id}>{n.title}</span>)}</div></>}
{s.phase==='auto'&&<ol className="work-list">{s.nodes[0].substeps.map(n=><li key={n.id} className={n.status}><span className="step-mark">{n.status==='completed'?'✓':''}</span><div><strong>{n.title}</strong><small>{n.status==='completed'?n.result:n.status==='in_progress'?'正在处理…':'稍后继续'}</small></div></li>)}</ol>}
{candidate&&<><div className="evaluation-steps" aria-label="候选判断进度"><span className="done">发现候选</span><span className={s.phase!=='candidate'?'done':''}>判断是否值得</span><span className={s.phase==='autoRelation'?'done':''}>{recalled?'留给你':'不打扰'}</span></div>{s.phase==='candidate'?<p className="screen-lead">文档、表格、知识库怎样连起来，会影响听众理解。这次需要你亲自拿主意吗？</p>:recalled?<p className="screen-lead">你希望多留一些练习机会，这个判断也值得一起做。</p>:<><p className="screen-lead">讲课主线已经明确，关系页也容易修改。YourTurn 判断这次可以继续，不必再叫你回来。</p><div className="quiet-result"><span>✓</span>一个候选，评估后没有打扰你。</div></>}{s.phase==='autoRelation'&&<div className="relation">文档 → 表格 → 知识库 → 团队归档</div>}</>}
{s.phase==='autoMain'&&<p className="screen-lead">你没有固定保留这类判断，Agent 根据当前设置先安排，再把结果留在路径里。</p>}
{s.phase==='autoInteraction'&&<><p className="screen-lead">结合当前参与设置，沿用 Dawn 已知的低压力表达习惯。</p><div className="quiet-result">没有新增邀请，成果中会标记为 AI 代选。</div></>}
{s.phase==='clientChange'&&<><p className="screen-lead">任务路径还在，哪一步要变，一眼能找到。</p><blockquote className="precise-edit">客户改了听众，先改「课堂用什么例子」。<br/>资料和讲课逻辑保留，后面的相关内容接着更新。</blockquote><p className="message-context">这是 YourTurn 留的兜底：随时回到路径，从需要你的那一步介入。</p></>}
{s.phase==='rerunning'&&<><p className="screen-lead">主线和前面的资料保留，相关内容从这里更新。</p><ol className="work-list revised-nodes">{s.nodes.map(n=><li key={n.id} className={n.status}><span className="step-mark">{n.status==='completed'?'✓':''}</span><strong>{n.title}</strong><small>{n.order<3?'保留':n.status==='completed'?'已更新':n.status==='in_progress'?'进行中':'待更新'}</small></li>)}</ol></>}
</Card>}
function Recap({s}){const a=s.artifacts.at(-1),count=Object.values(a.actors).filter(x=>x==='Dawn').length,quiet=s.recallDecisions.filter(d=>d.action==='AUTO').length;return <Card className="recap-card" title="你的判断，让这堂课有了自己的讲法。" footer={<><Button onClick={()=>act('OPEN_VIEW',{view:'artifact'})}>查看培训方案</Button><Button primary onClick={()=>act('SHOW_LEARNING')}>用一个月后呢？ →</Button></>}><p className="recap-total">这次，Agent 邀请你判断了 {count} 次{s.version>1?'，你还主动改了 1 处。':'。'}</p><div className="recap-impact"><div><span className="impact-number">01</span><div><h3>{a.actors.main==='Dawn'?'你练了讲课逻辑的判断':'Agent 沿用偏好安排主线'}</h3><p>{a.main}</p></div></div><div><span className="impact-number">02</span><div><h3>{a.actors.interaction==='Dawn'?'你选了自己说得出口的互动':'Agent 沿用低压力的表达'}</h3><p>{a.interaction}</p></div></div>{a.actors.relation==='Dawn'&&<div><span className="impact-number">03</span><div><h3>你决定怎样讲清工具关系</h3><p>{a.relationFormat}</p></div></div>}{s.version>1&&<div><span className="impact-number">↗</span><div><h3>客户变了，只改受影响的部分</h3><p>保留资料和讲课逻辑，更新例子及后续内容。</p></div></div>}</div>{quiet>0&&<div className="quiet-result"><span>✓</span>{quiet} 个候选评估后继续 Auto，少打扰你 {quiet} 次。</div>}</Card>}
function Learning({s}){const initial=s.learningStep==='initial',done=s.learningStep==='done';useEffect(()=>{if(s.view!=='task'||done)return;const timer=setTimeout(()=>act(initial?'ADVANCE_LEARNING':'SETTLE_LEARNING',{run:s.learningRun}),initial?scenario.learning.holdMs:scenario.learning.animateMs);return()=>clearTimeout(timer)},[s.learningRun,s.learningStep,s.view]);return <Card className="learning-card" title="一个月后，更懂哪些判断值得留给你。" footer={<>{done&&<Button onClick={()=>act('REPLAY_LEARNING')}>再看一次变化</Button>}<Button primary disabled={!done} onClick={()=>act('FINISH_DEMO')}>{done?'完成体验 ✓':'正在了解 Dawn…'}</Button></>}><div className="time-transition" aria-live="polite"><span className={initial?'active':''}>初次使用</span><span className="time-line"/><span className={!initial?'active':''}>一个月后</span></div><p className="learning-context">{initial?'刚开始，还不太清楚你想把哪些判断留给自己。':'你反复保留的练习，和只有你知道的表达，逐渐变得清晰。'}</p><div className="animated-weights" key={s.learningRun}>{scenario.learning.labels.map((label,i)=><div className="animated-weight" key={label}><div className="weight-caption"><span>{label}</span><b>{s.weights[i]}%</b></div><div className="weight-track" role="progressbar" aria-label={label} aria-valuemin={0} aria-valuemax={100} aria-valuenow={s.weights[i]}><span style={{width:s.weights[i]+'%',transitionDuration:scenario.learning.animateMs+'ms'}}><i/></span></div></div>)}</div><div className={'future-routes animation-result '+(done ? 'settled' : '')} aria-label="未来的判断分配">{scenario.learning.candidates.map(n=><div key={n.title}><strong>{n.title}</strong><span className={'route '+(learningDecision(s.weights,n.tags)==='AUTO'?'auto':'recall')}>{learningDecision(s.weights,n.tags)==='AUTO'?'Auto':'YourTurn'}</span></div>)}</div></Card>}
function CustomerMessage(){return <aside className="customer-notification" role="status" aria-label="客户的新消息"><div className="notification-top"><span className="chat-mark">···</span><strong>银行客户</strong><small>刚刚</small></div><p>{copy.message}</p><div className="notification-reaction">……甲方又改需求了。</div><Button primary onClick={()=>act('CLIENT_CHANGE')}>去看哪里要改 →</Button></aside>}
function Ready({s}){return <Card className={'ready-card '+(s.clientMessageVisible ? 'has-notification' : '')} title="这版，可以去备课了。" footer={<Button onClick={()=>act('OPEN_VIEW',{view:'artifact'})}>查看培训方案</Button>}><div className="delivery-check">✓</div><h3>60 分钟培训方案，已整理好。</h3><p className="screen-lead">讲课的逻辑和互动方式，都沿着你的判断继续。</p>{s.clientMessageVisible&&<CustomerMessage/>}</Card>}
function Finished({s}){return <Card className="finished-card" title="判断留给你，执行交给 Agent。" footer={<Button primary onClick={()=>act('OPEN_VIEW',{view:'artifact'})}>带走这份培训方案 ↓</Button>}><div className="delivery-check">✓</div><h3>这次备课，到这里就完成了。</h3><p className="screen-lead">Dawn 留下了自己的讲法，也练习了值得保留的判断。</p><p className="ending-note">以后需要你时，YourTurn 再叫你回来。</p></Card>}
function downloadArtifact(a){const url=URL.createObjectURL(new Blob([artifactMarkdown(a)],{type:'text/markdown;charset=utf-8'})),link=document.createElement('a');link.href=url;link.download=`Dawn-training-v${a.version}.md`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function Pager({page,total,onChange}){return <div className="pager"><Button disabled={page===0} onClick={()=>onChange(page-1)}>←</Button><span>{page+1} / {total}</span><Button disabled={page===total-1} onClick={()=>onChange(page+1)}>→</Button></div>}
function Artifact({s}){const a=currentArtifact(s),page=Math.min(s.page,3);return <Card title={['60 分钟，怎样讲完','课堂里的例子','现场互动与讲稿','课件顺序'][page]} footer={<><Button onClick={()=>act('CLOSE_VIEW')}>回到任务</Button><Pager page={page} total={4} onChange={page=>act('VIEW_PAGE',{page})}/><Button onClick={()=>downloadArtifact(a)}>下载方案 ↓</Button></>}><div className="artifact-toolbar"><span>V{a.version} · {a.audience}</span>{s.artifacts.length>1&&<select aria-label="成果版本" value={a.version} onChange={e=>act('VIEW_ARTIFACT_VERSION',{version:Number(e.target.value)})}>{s.artifacts.map(x=><option key={x.version} value={x.version}>V{x.version}{x.version===1?' · 首轮':' · 修改后'}</option>)}</select>}</div>{page===0&&<div className="agenda">{a.agenda.map(x=><div key={x.title}><span>{x.minutes}′</span><strong>{x.title}</strong></div>)}</div>}{page===1&&<><h3>{a.caseTitle}</h3><ol className="case-steps">{a.caseSteps.map(x=><li key={x}>{x}</li>)}</ol><div className="relation">{a.relationFormat}<br/>{a.relation}</div></>}{page===2&&<><h3>{a.interaction}</h3><blockquote>{a.script}</blockquote><p>{a.interactionImpact}</p>{a.pendingRequirements.length>0&&<p className="muted">另有 {a.pendingRequirements.length} 条补充要求随下载保留，需要人工应用。</p>}</>}{page===3&&<ol className="slide-list">{a.slides.map(x=><li key={x}>{x}</li>)}</ol>}</Card>}
function History({s}){const page=Math.min(s.page,Math.max(0,s.log.length-1)),entry=s.log[page];return <Card title="回看这次过程" footer={<><Button onClick={()=>act('CLOSE_VIEW')}>回到任务</Button><Pager page={page} total={Math.max(1,s.log.length)} onChange={page=>act('VIEW_PAGE',{page})}/></>}><div className="history-entry"><h3>{entry?.role}</h3><p>{entry?.text}</p></div></Card>}
function Settings({s,onClose}){return <Card title="你想怎样参与" footer={<Button primary onClick={onClose}>保存设置</Button>}><label className="retain-setting"><input type="checkbox" checked={s.retainedJudgments.main} onChange={e=>act('SET_RETAIN_MAIN',{value:e.target.checked})}/><span>讲课逻辑，每次都留给我判断</span></label><h3>其他判断</h3><Modes s={s}/><div className="preference-grid">{[0,3].map(i=>{const q=scenario.questions[i];return <label key={i}><span>{i===0?'什么时候问我':'最多问几次'}</span><select aria-label={q.question} value={s.profileDraft.answers[i]} onChange={e=>{const answers=[...s.profileDraft.answers];answers[i]=Number(e.target.value);act('PROFILE_DRAFT',{patch:{answers}});}}>{q.options.map(([label],i)=><option key={label} value={i}>{label}</option>)}</select></label>})}</div></Card>}
function usePlayback(s,suspended){const [visible,setVisible]=useState(!document.hidden);useEffect(()=>{const onChange=()=>setVisible(!document.hidden);document.addEventListener('visibilitychange',onChange);return()=>document.removeEventListener('visibilitychange',onChange)},[]);const key=playbackKey(s),delay=scenario.playbackMs[s.phase];useEffect(()=>{if(!delay||s.playbackPaused||!visible||suspended||s.view!=='task')return;const timer=setTimeout(()=>act('AUTO_TICK',{key}),delay);return()=>clearTimeout(timer)},[key,delay,s.playbackPaused,visible,suspended,s.view]);useEffect(()=>{if(s.phase!=='complete'||s.clientMessageVisible||s.clientMessageDismissed||!visible||suspended||s.view!=='task')return;const timer=setTimeout(()=>act('CLIENT_MESSAGE'),3500);return()=>clearTimeout(timer)},[s.phase,s.finalAcceptedAt,s.clientMessageVisible,s.clientMessageDismissed,visible,suspended,s.view])}
function App(){const s=useSyncExternalStore(store.subscribe,store.getSnapshot),localCall=useMemo(()=>(endpoint,payload)=>plugin.call(endpoint,payload),[s.revision]);const[modal,setModal]=useState(null),[resetKey,setResetKey]=useState(0);usePlayback(s,!!modal);useEffect(()=>{if(s.phase==='path'&&window.innerWidth>850)openPath()},[s.phase]);useEffect(()=>{const onKey=e=>{if(e.key==='Escape')setModal(null)};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[]);
const installed=!['install','installing'].includes(s.phase),onboarding=s.phase==='onboarding',hasTask=s.nodes.length>0;const stage=!installed?0:onboarding?1:['complete','recap','updated','learning','finished','clientChange','rerunning'].includes(s.phase)?3:2;
let content=s.view==='artifact'?<Artifact s={s}/>:s.view==='history'?<History s={s}/>:['install','installing'].includes(s.phase)?<Install s={s}/>:onboarding?<Onboarding s={s}/>:['main','relation','interaction'].includes(s.phase)?<Recall s={s} onNote={()=>setModal('note')}/>:s.phase==='learning'?<Learning s={s}/>:s.phase==='complete'?<Ready s={s}/>:s.phase==='finished'?<Finished s={s}/>:['recap','updated'].includes(s.phase)?<Recap s={s}/>:<Execution s={s}/>;
return <div className={`app single-screen phase-${s.phase} ${modal?'has-modal':''} ${s.view!=='task'?'reading-view':''}`}><header className="topbar"><div className="brand"><img className="yourturn-logo" src="./yourturn-logo.png" alt="YourTurn"/><span className="brand-context"><img className="dsh-whale" src="./deepseek-logo.svg" alt=""/>DeepSeek Harness 插件</span></div><div className="actions">{installed&&<button className="preference-trigger" aria-label="参与设置" title="参与设置" onClick={()=>setModal('settings')}><Icon kind="settings"/></button>}<button className="text-button about-button" onClick={()=>setModal('info')}>关于</button><button className="text-button" onClick={()=>setModal('reset')}>重新开始</button></div></header>
<aside className="profile-sidebar">{installed?<><img src={copy.portrait} alt="Dawn 的头像"/><h2>Dawn</h2><p>毕业一年<br/>企业培训讲师</p><div className="profile-rule"><span>想练习的判断</span><strong>怎样组织讲课逻辑</strong><strong>怎样把握现场节奏</strong></div><p className="profile-context">选出适合自己的表达，<br/>上台时更从容一点。</p></>:<div className="plugin-side"><img className="yourturn-logo" src="./yourturn-logo.png" alt="YourTurn"/><p>和你已有的 Agent<br/>一起工作</p></div>}</aside>
<main className="workspace"><nav className="demo-progress" aria-label="演示进度"><ol>{['启用插件','认识 Dawn','一起备课','收尾与回顾'].map((label,i)=><li key={label} className={i===stage?'current':i<stage?'complete':''} aria-current={i===stage?'step':undefined}><span>{i<stage?'✓':i+1}</span>{label}</li>)}</ol></nav><div className="screen-stage">{hasTask?<><span>{s.view==='task'?`${copy.modes[s.taskProfile.participationGoal]?.[0]} · 已邀请 ${s.recallState.recallCount} 次`:'本次任务记录'}</span><button onClick={openPath} className="text-button">任务路径 · {s.nodes.filter(n=>n.status==='completed').length}/6</button></>:<span>让 Agent 更懂什么时候需要你</span>}</div><div className="screen-content">{content}</div><footer className="screen-tools">{hasTask&&s.view==='task'&&<button onClick={()=>act('OPEN_VIEW',{view:'history'})}><Icon kind="history"/>回看过程</button>}{s.artifacts.length>0&&s.view==='task'&&!['complete','updated'].includes(s.phase)&&<button onClick={()=>act('OPEN_VIEW',{view:'artifact'})}><Icon kind="file"/>培训方案</button>}</footer></main>
<OriginalPlugin key={resetKey} call={localCall}/>
{modal&&<div className="modal-scrim"><div className="screen-modal" role="dialog" aria-modal="true" aria-label={modal==='settings'?'参与设置':modal==='note'?'补充想法':modal==='reset'?'重新开始演示':'关于 YourTurn'}>{modal==='settings'?<Settings s={s} onClose={()=>{if(s.preferenceProfile){act('START_PREFERENCE_ONBOARDING');act('SAVE_PROFILE')}setModal(null)}}/>:modal==='note'?<Card title="补充你的想法" footer={<Button primary onClick={()=>setModal(null)}>保留这条备注</Button>}><textarea className="note-input" aria-label="补充你的判断" rows={4} maxLength={280} value={s[`${s.phase}Note`]||''} onChange={e=>act('ANSWER_DRAFT',{note:e.target.value})}/><p className="muted">备注会随方案保存，供后续调整。</p></Card>:modal==='reset'?<Card title="从头体验一次？" footer={<><Button onClick={()=>setModal(null)}>继续当前任务</Button><Button primary onClick={()=>{act('RESET');setResetKey(k=>k+1);setModal(null)}}>确认重新开始</Button></>}><p>本次判断和成果会清空。</p></Card>:<Card title="YourTurn 是一个 Agent 插件" footer={<Button primary onClick={()=>setModal(null)}>知道了</Button>}><p>真实实现运行在 DeepSeek Harness 中。它利用任务、个人偏好与当前情境，决定何时继续 Auto、何时邀请你参与。</p><p>这里使用本地情境体验；启用按钮仅在演示中生效，不会给你的真实 Agent 安装插件。选项会改变方案，自由文字只作备注。</p><p>未来权重用于展示产品机制，尚非长期实测；真实 Agent 不保证每次选择相同节点。</p><a href={`https://github.com/your-turn-lab/your-turn-dsh/tree/${scenario.sourceBranch}`} target="_blank" rel="noreferrer">查看真实插件源码 ↗</a></Card>}</div></div>}
</div>}
createRoot(document.getElementById('app')).render(<App/>);
